// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team4993.Molly.subsystems;

import org.usfirst.frc.team4993.Molly.RobotMap;
import org.usfirst.frc.team4993.Molly.commands.Lift;
import org.usfirst.frc.team4993.Molly.commands.SolOff;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Arms extends Subsystem {
    
    public static Compressor compressor1 = RobotMap.armsCompressor1;
	public static Solenoid solenoid1 = RobotMap.armsSolenoid1;
    public static Solenoid solenoid2 = RobotMap.armsSolenoid2;
    public static Solenoid solenoid3 = RobotMap.armsSolenoid3;
    public static Solenoid solenoid4 = RobotMap.armsSolenoid4;

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    	setDefaultCommand(new SolOff());
    }
    
    public static void On(){
    	solenoid1.set(true);
    	solenoid2.set(false);
    	solenoid3.set(false);
    	solenoid4.set(true);	
    }
    
    public static void Down(){
    	solenoid1.set(false);
    	solenoid2.set(true);
    	solenoid3.set(true);
    	solenoid4.set(false);
    }
    
    public static void AuLift(){
    	solenoid1.set(true);
    	solenoid2.set(false);
    	solenoid3.set(false);
    	solenoid4.set(true);
    	Timer.delay(8.0);
    	solenoid1.set(false);
    	solenoid2.set(true);
    	solenoid3.set(true);
    	solenoid4.set(false);
    }
	
    public static void Off(){
		solenoid1.set(false);
    	solenoid2.set(false);
    	solenoid3.set(false);
    	solenoid4.set(false);
	}
}

